import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/Context/UserContext";
import Navbar from "@/components/Navbar/Navbar";
import { ArticleProvider } from "@/Context/ArticleContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col h-screen">
          <AuthProvider>
            <ArticleProvider>
            <Navbar/>
            {children}
            </ArticleProvider>
          </AuthProvider>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
